### ISSUE TITLE
User Connect INI

### ISSUE THREAD

**Issue by Soyrce** [byjumpe/AMXX-Plugins#1]
why you hook a file that is an .INI that identifies the players who have entered SERVER, why not include it as a cache in fvault and print the cached players or who will allow them to log in?

**Comment by byjumpe** [comment]
why? what will it do?

**Comment by Soyrce** [comment]
What did you try to do with this code anyway?

I think you will make it load ARRAY .INI Anyone who accesses it can access SERVER
